name: Open Liberty
version: 0.1.0
description: Eclipse MicroProfile & Jakarta EE on Open Liberty & OpenJ9 using Maven
license: Apache-2.0
language: java
maintainers:
  - name: Joe
    email: jdmcclur@us.ibm.com
    github-id: jdmcclur
default-template: default
requirements:
    docker-version: ">= 17.09.0"
    appsody-version: ">= 0.5.0"
templating-data:
    libertyversion: '20.0.0.5'
    parentpomgroup: 'dev.appsody'
    parentpomid: 'acmeair-stack'
    parentpomrange: '[0.1, 0.2)'
